Restaurant/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("details.urls")),
    path("accounts/", include("accounts.urls")),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

details/urls.py
from django.urls import path, include
from . import views


urlpatterns = [
    path("", views.home, name="home"),
    path("about/", views.about, name="about"),
    path("book/", views.book, name="book"),
    path("reservations/", views.reservations, name="reservations"),
    path("menu/", views.menu, name="menu"),
    path("menu_item/<int:pk>/", views.display_menu_item, name="menu_item"),
    path("bookings/", views.bookings, name="bookings"),
    path("today_reservation/", views.today_reservation, name="today_reservation"),
    path("editbooking/<uuid:bookingId>/", views.edit_booking, name="edit_booking"),
    path("feedback/<uuid:bookingId>/", views.feedback, name="feedback"),
]

details/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.contrib.auth.models import User
from datetime import date, time
import uuid
from django.core.exceptions import ValidationError

STATUS_CHOICES = (
    ("pending", "Pending"),
    ("confirmed", "Confirmed"),
    ("cancelled", "Cancelled"),
    ("checkedout", "Checkedout"),
)


class Booking(models.Model):
    # Customer Details
    user = models.ForeignKey(User, default=None, on_delete=models.CASCADE)
    first_name = models.CharField(null=False, default="", max_length=100)
    last_name = models.CharField(null=False, default="", max_length=100)
    email = models.EmailField(default="", null=False, max_length=100)
    phone_number = models.CharField(default="", null=False, max_length=20)

    # Reservation Details
    reservation_date = models.DateField(default=date.today, null=False)
    reservation_time = models.TimeField()
    party_size = models.PositiveIntegerField(default=2)
    # Special Requests or Comments (optional)
    special_requests = models.TextField(
        blank=True, default="Thankyou for asking!!, No special request for now"
    )

    # Timestamps
    created_at = models.DateField(auto_now=True, editable=False)
    updated_at = models.TimeField(auto_now=True, editable=False)
    # Status of the Booking
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default="pending")

    # New field: Booking ID
    bookingId = models.UUIDField(default=uuid.uuid4, editable=False, unique=True)

    def __str__(self):
        return f"{self.first_name} {self.last_name} {self.reservation_date} {self.reservation_time}"


class Category(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name


class Menu(models.Model):
    category = models.ForeignKey(Category, default=None, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    price = models.DecimalField(max_digits=5, decimal_places=2, null=False)
    menu_item_description = models.TextField(
        max_length=1000, default="No description available"
    )
    is_available = models.BooleanField(default=True)
    is_special = models.BooleanField(default=True)
    is_recommended = models.BooleanField(default=True)

    calories = models.DecimalField(
        max_digits=5, decimal_places=2, null=True, blank=True
    )
    fat_content = models.DecimalField(
        max_digits=5, decimal_places=2, null=True, blank=True
    )
    allergens = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        return f"{self.name}__{self.category}"


class MenuImage(models.Model):
    menu = models.ForeignKey(Menu, on_delete=models.CASCADE)
    images = models.ImageField(
        upload_to="menu_images/",
        validators=[FileExtensionValidator(["jpg", "jpeg", "png"])],
        null=True,
        blank=True,
    )
    created_at = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.menu.name}--{self.menu.category}"


class Feedback(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    bookingId = models.ForeignKey(Booking, null=False, on_delete=models.CASCADE)
    feed_date = models.DateField(auto_now=True, null=False)
    rating = models.PositiveIntegerField(default=0)
    message = models.TextField(null=False, max_length=800)

    def __str__(self) -> str:
        return f"{self.user.username}--{self.bookingId}"


class FeedImage(models.Model):
    feedback = models.ForeignKey(Feedback, on_delete=models.CASCADE)
    images = models.FileField(
        upload_to="feedimage/",
        validators=[FileExtensionValidator(["jpg", "jpeg", "png"])],
        null=True,
    )
    date = models.DateField(auto_now=True)

    def __str__(self) -> str:
        return f"{self.feedback.user.username}--{self.date}"

templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="about-section mt-5">
  <div class="container">
    <div class="row align-items-center">
      <div class="col-md-7">
        <h1 class="mb-4">About Us</h1>
        <span class="d-flex p-4">
          <h3>Current Rating : </h3>
          <p class="average_rating">{{ average_rating|floatformat:1 }} &#9733;</p>
        </span>
      </div>
      <div class="col-md-5">
        <figure class="figure">
          <img src="{% static '' %}" alt="owner" class="img-fluid rounded shadow">
          <figcaption class="figure-caption mt-2">
            Restaurant owners
          </figcaption>
        </figure>
      </div>
    </div>

  </div>
</section>
<div class="container mb-5">
  <h1 class="text-center mb-5">Feedbacks</h1>
  <div class="row row-cols-1 row-cols-md-2 g-4">
    {% for feedback in feedbacks %}
    <div class="col">
      <div class="card h-100">
        <div class="card-body">
          <h5 class="card-title">{{ feedback.user.username }}</h5>
          <p class="card-text">Date: {{ feedback.feed_date }}</p>
          <div class="d-flex align-items-center mb-3">
            <p class="mb-0 me-2">Rating:</p>
            <div class="rating">
              {{feedback.rating}}
              &#9733;
            </div>
          </div>
          <p class="card-text">{{ feedback.message }}</p>
        </div>
        <div class="carousel slide" data-bs-ride="carousel" id="carousel-{{ feedback.id }}">
          <div class="carousel-indicators">
            {% for image in feedback.feedimage_set.all %}
            <button type="button" data-bs-target="#carousel-{{ feedback.id }}" data-bs-slide-to="{{ forloop.counter0 }}"
              {% if forloop.first %}class="active" {% endif %}></button>
            {% endfor %}
          </div>
          <div class="carousel-inner">
            {% for image in feedback.feedimage_set.all %}
            <div class="carousel-item {% if forloop.first %}active{% endif %}">
              <img src="{{ image.images.url }}" class="d-block w-100 img-carousel" alt="Feedback Image">
            </div>
            {% endfor %}
          </div>
          <button class="carousel-control-prev" type="button" data-bs-target="#carousel-{{ feedback.id }}"
            data-bs-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Previous</span>
          </button>
          <button class="carousel-control-next" type="button" data-bs-target="#carousel-{{ feedback.id }}"
            data-bs-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="visually-hidden">Next</span>
          </button>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
  <div class="d-flex justify-content-center mt-4">
    <div class="pagination">
      <span class="step-links">
        {% if feedbacks.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ feedbacks.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current-page">
          Page {{ feedbacks.number }} of {{ feedbacks.paginator.num_pages }}.
        </span>

        {% if feedbacks.has_next %}
        <a href="?page={{ feedbacks.next_page_number }}">next</a>
        <a href="?page={{ feedbacks.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
      </span>
    </div>
  </div>
</div>
<div class="column">
</div>
<style>
  .rating {
    color: #259c07;
    font-size: 1.2rem;
    font-weight: bolder
  }

  .carousel {
    margin-top: 15px;
  }

  .carousel-inner {
    border-radius: 10px;
    overflow: hidden;
  }

  .carousel-item img {
    object-fit: cover;
    height: 300px;
  }

  .pagination {
    display: flex;
    justify-content: center;
    align-items: center;
    margin-top: 20px;
  }

  .step-links {
    display: flex;
    align-items: center;
    margin-right: 10px;
  }

  .step-links a {
    padding: 5px;
    text-decoration: none;
    border: 1px solid #ddd;
    border-radius: 5px;
    margin-right: 5px;
  }

  .current-page {
    font-weight: bold;
    margin: 0 10px;
  }

  .average_rating {
    background-color: #259c07;
    border-radius: 100px;
    padding: 2px;
    color: blanchedalmond;
    font-weight: bolder;
    font-size: 1.5rem;
  }
</style>
{% endblock %}

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />

  <title>Restaurant</title>
  <meta name="description" content="A brief description" />
  <meta name="author"
    content="It is a family owned Mediterranean restaurant, focused on traditional recipes served with a modern twist." />

  <!-- Load favicon -->
  <link rel="shortcut icon" type="image/png" href="{% static '' %}" />

  <!-- Include your CSS files here -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-4bw+/aepP/YC94hEpVNVgiZdgIC5+VKNBQNGCHeKRQN+PtmoHDEXuppvnDJzQIu9" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
  <link rel="preload" as="style" href="{% static 'css/base.css' %}" onload="this.rel = 'stylesheet'" />

  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Karla&family=Markazi+Text:wght@500&display=swap"
    rel="stylesheet" />

</head>

<body>
  <!--Header content-->
  <div id="navbar">
    {% include 'partials/_header.html' %}
  </div>

  <main>{% block content %} {% endblock %}</main>

  <!--Footer content-->
  {% include 'partials/_footer.html' %}
  <!-- Replace this comment with your code  -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-HwwvtgBNo3bZJJLYd8oVXjrBZt8cqVSpeBNS5n7C8IVInixGAoxmnlMuBnhbgrkm" crossorigin="anonymous"></script>
</body>

</html>

templates/book.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="col-md-12">
  {% if messages %}
  <div class="messages">
    {% for message in messages %}
    <div {% if message.tags %} class="alert {{ message.tags }}" {% endif %}>
      {{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
  </div>
  {% endif %}
</div>
<section>
  <article>
    <div class="container">
      <h1 class="text-center mb-4">Make a Reservation</h1>
      <div class="row">
        <div class="col-md-5">
          {% if request.user.is_authenticated %}
          <p class="text-primary">Welcome, {{ request.user }}</p>
          {% else %}
          <p class="text-warning">Please login to make a booking</p>
          {% endif %}
          <form method="post" id="form">
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-3">
              <label for="{{ field.id_for_label }}" class="form-label">{{ field.label }}</label>
              {{ field }}
              {% if field.errors %}
              <div class="invalid-feedback">
                {{ field.errors|join:", " }}
              </div>
              {% endif %}
            </div>
            {% endfor %}
            <div class="d-flex justify-content-between mt-3">
              <button type="submit" id="button" class="btn btn-lg btn-primary">Book Now</button>
              <button type="reset" id="button" class="btn btn-lg btn-danger">Clear</button>
            </div>
          </form>
        </div>
        <div class="col-md-7">
          <h2 class="mb-3">Bookings For <span id="today"></span></h2>
          <div id="bookings"></div>
        </div>
      </div>
    </div>
  </article>
</section>

<style>
  .booking-card {
    background-color: #f8f9fa;
    border-radius: 10px;
    padding: 10px;
    margin: 10px 0;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }

  .messages {
    margin-bottom: 15px;
  }

  .alert {
    margin-bottom: 15px;
    position: relative;
    padding: 0.75rem 1.25rem;
    border: 1px solid transparent;
    border-radius: 0.25rem;
  }

  .alert.alert-success {
    color: #155724;
    background-color: #d4edda;
    border-color: #c3e6cb;
  }

  .alert.alert-danger {
    color: #721c24;
    background-color: #f8d7da;
    border-color: #f5c6cb;
  }
</style>

<style>
  .booking-card {
    background-color: #f8f9fa;
    border-radius: 10px;
    padding: 10px;
    margin: 10px 0;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }
</style>

<script>
  function getBookings() {
    const dateInput = document.getElementById("reservation_date");
    let selectedDate = dateInput.value;

    if (!selectedDate) {
      // If no date is selected, use the current date as the default
      const currentDate = new Date();
      selectedDate = `${currentDate.getFullYear()}-${currentDate.getMonth() + 1
        }-${currentDate.getDate().toString().padStart(2, "0")}`;
      dateInput.value = selectedDate;
    }

    document.getElementById("today").innerHTML = selectedDate;

    fetch("{% url 'today_reservation' %}" + "?date=" + selectedDate, { method: "GET" })
      .then((response) => response.json())
      .then((data) => {
        let bookings = "";

        for (let i = 0; i < data.length; i++) {
          const item = data[i];
          // console.log(item.fields);
          // Show all item fields in the bookings section
          bookings += `<div class = "booking-card">`
          bookings += `<p>Name : ${item.fields.first_name} ${item.fields.last_name
            }</p>
          <p> Email : ${item.fields.email}</p>
          <p> Phone No. : ${item.fields.phone_number}</p>
          <p> Reservation date : ${item.fields.reservation_date}</p>
        <p> Reservation time : ${formatTime(item.fields.reservation_time)}</p>
        <p> Party size : ${item.fields.party_size}</p>
        <p> Booked at : ${item.fields.created_at}</p>
        <p> Booking Id : ${item.fields.bookingId}</p>
        <p> Booking updated at : ${formatTime(item.fields.updated_at)}</p>
        <p> Special requests: ${item.fields.special_requests}</p>
        <p> Booking status: ${item.fields.status}</p>
        </div>`;
        }

        if (bookings === "") {
          bookings = "No bookings";
        }
        document.getElementById("bookings").innerHTML = bookings;
      });
  }

  getBookings();

  function formatTime(time) {
    const ampm = time < 12 ? "AM" : "PM";
    const t = time < 12 ? time : time > 12 ? time - 12 : time;
    const label = `${t} ${ampm}`;
    return label;
  }

  document
    .getElementById("reservation_date")
    .addEventListener("change", function () {
      getBookings();
    });
</script>
{% endblock %}

templates/bookings.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
<div class="col-md-12">
  {% if messages %}
  <div class="messages">
    {% for message in messages %}
    <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
    {% endfor %}
  </div>
  {% endif %}
</div>
<section class="py-5">
  <div class="container">
    <h1 class="text-center mb-4">Your Reservations</h1>
    <div class="row">
      <!-- Upcoming Reservations -->
      <div class="col-md-6">
        <h2 class="mb-3">Upcoming Reservations</h2>
        {% if request.user.is_authenticated %}
        <div id="upcoming-bookings" class="d-flex flex-wrap"></div>
        {% else %}
        <p class="text-primary">Please log in to view your upcoming reservations.</p>
        {% endif %}
      </div>
      <!-- Previous Reservations -->
      <div class="col-md-6">
        <h2 class="mb-3">Previous Reservations</h2>
        {% if request.user.is_authenticated %}
        <div id="previous-reservations" class="d-flex flex-wrap"></div>
        {% else %}
        <p class="text-warning">Please log in to view your previous reservations.</p>
        {% endif %}
      </div>
    </div>
  </div>
</section>

<style>
  .booking-card {
    background-color: #f8f9fa;
    border-radius: 10px;
    padding: 10px;
    margin: 10px 0;
    box-shadow: 0 2px 4px rgba(0, 0, 0, 0.1);
  }
</style>


<script>
  // Fetch reservations data
  fetch("{% url 'reservations' %}", {
    method: "GET"
  }).then((response) => response.json())
    .then((data) => {
      console.log(data);
      const upcomingBookingsData = document.getElementById("upcoming-bookings");
      const previousBookingsData = document.getElementById("previous-reservations");
      let upcomingHtml = "";
      let previousHtml = "";

      data.upcoming_bookings.forEach((booking) => {
        upcomingHtml += "<div class='booking-card text-wrap'>";
        upcomingHtml += `<p> <b> Booking Id: </b> ${booking.bookingId}</p>`;
        upcomingHtml += `<p> <b> Name: </b>${booking.first_name} ${booking.last_name}</p>`;
        upcomingHtml += `<p> <b> Email: </b>${booking.email}</p>`;
        upcomingHtml += `<p> <b> Phone Number: </b>${booking.phone_number}</p>`;
        upcomingHtml += `<p> <b> Date: </b>${booking.reservation_date}</p>`;
        upcomingHtml += `<p> <b> Time: </b>${formatTime(booking.reservation_time)}</p>`;
        upcomingHtml += `<p> <b> Party Size: </b>${booking.party_size}</p>`;
        upcomingHtml += `<p> <b> Status: </b>${booking.status}</p>`;
        upcomingHtml += `<p> <b> Special Requests: </b>${booking.special_requests}</p>`;
        upcomingHtml += `<a href="../feedback/${booking.bookingId}" class="btn btn-sm btn-secondary mx-2">Give Feedback</a>`;
        upcomingHtml += `<a href="../editbooking/${booking.bookingId}" class="btn btn-sm btn-warning mx-2">Edit</a>`;
        upcomingHtml += "</div>";

      });

      data.previous_bookings.forEach((booking) => {
        previousHtml += "<div class='booking-card text-wrap'>";
        previousHtml += `<p> <b> Booking Id: </b> ${booking.bookingId}</p>`;
        previousHtml += `<p> <b> Name: </b>${booking.first_name} ${booking.last_name}</p>`;
        previousHtml += `<p> <b> Email: </b>${booking.email}</p>`;
        previousHtml += `<p> <b> Phone Number: </b>${booking.phone_number}</p>`;
        previousHtml += `<p> <b> Date: </b>${booking.reservation_date}</p>`;
        previousHtml += `<p> <b> Time: </b>${formatTime(booking.reservation_time)}</p>`;
        previousHtml += `<p> <b> Party Size: </b>${booking.party_size}</p>`;
        previousHtml += `<p> <b> Status: </b>${booking.status}</p>`;
        previousHtml += `<p> <b> Special Requests: </b>${booking.special_requests}</p>`;
        previousHtml += `<a href="../feedback/${booking.bookingId}" class="btn btn-sm btn-secondary">Give Feed</a>`;
        previousHtml += "</div>";
      });

      // Set the HTML for upcoming and previous bookings
      upcomingBookingsData.innerHTML = upcomingHtml || "<p>No upcoming bookings.</p>";
      previousBookingsData.innerHTML = previousHtml || "<p>No previous bookings.</p>";
    })
    .catch((error) => {
      // Handle any errors that occurred during the fetch
      console.error("Error fetching bookings data:", error);
      const upcomingBookingsData = document.getElementById("upcoming-bookings");
      upcomingBookingsData.innerHTML = "<p>Error fetching bookings data.</p>";
      const previousBookingsData = document.getElementById("previous-reservations");
      previousBookingsData.innerHTML = "<p>Error fetching bookings data.</p>";
    });

  function formatTime(time) {
    const ampm = time < 12 ? "AM" : "PM";
    const t = time < 12 ? time : time > 12 ? time - 12 : time;
    const label = `${t} ${ampm}`;
    return label;
  }
</script>
{% endblock %}

templates/editbooking.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<section class="py-5">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <h1 class="card-title text-center mb-4">Edit Booking</h1>
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                            <div class="mb-3">
                                {{ field.label_tag }}
                                {{ field }}
                                {% if field.help_text %}
                                <small class="form-text text-muted">{{ field.help_text }}</small>
                                {% endif %}
                                {% if field.errors %}
                                <ul class="errorlist">
                                    {% for error in field.errors %}
                                    <li>{{ error }}</li>
                                    {% endfor %}
                                </ul>
                                {% endif %}
                            </div>
                            {% endfor %}
                            <div class="d-flex justify-content-center">
                                <button type="submit" class="btn btn-primary me-1">Save Changes</button>
                                <a href="{% url 'bookings' %}" class="btn btn-secondary">Cancel</a>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<style>
    .card {
        border: none;
    }

    .errorlist {
        color: #dc3545;
        margin-top: 5px;
        list-style: none;
        padding-left: 0;
    }
</style>
{% endblock %}

templates/feedbackForm.html
{% extends 'base.html' %}

{% block content %}

<div class="col-md-12">
    {% if messages %}
    <div class="messages">
        {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endfor %}
    </div>
    {% endif %}
</div>
<h1 class="text-center mb-4">Feedback</h1>
<div class="container d-flex justify-content-center">
    {% if user.is_authenticated %}
    <form method="post" enctype="multipart/form-data" class="col-md-8">
        {% csrf_token %}
        {{ feedbackform.as_p }}
        <div class="mb-3">
            <label for="feedimage">Upload Images</label>
            <input type="file" name="images" id="images" class="form-control" multiple>
        </div>
        <div class="d-flex">
            <button type="submit" class="btn btn-primary">Submit</button>
            <button type="reset" class="btn btn-danger">Reset</button>
        </div>
    </form>
    {% else %}
    <p>Please login to submit feedback.</p>
    {% endif %}
</div>

{% endblock %}

templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="content-bg">
  <div class="col-md-12">
    {% if messages %}
    <div class="messages">
      {% for message in messages %}
      <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>{{ message }}
        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
      </div>
      {% endfor %}
    </div>
    {% endif %}
  </div>
  <section class="py-5">
    <article id="hero" class="text-center">
      <h1 class="display-4 fw-bold mb-3">SPECIAL OFFER</h1>
      <p class="lead">
        30% Off This Weekend
      </p>
      <a href="{% url 'book' %}" class="btn btn-primary btn-lg"> Book now </a>
    </article>
  </section>

  <section class="py-5">
    <div class="row">
      <div class="col-md-4">
        <article class="text-center mb-4">
          <h2 class="fw-bold">Our New Menu</h2>
          <img src="{% static 'img/menu.png' %}" alt="New Menu" class="img-fluid rounded shadow">
          <p class="mt-3">
            Our menu
          </p>
          <a href="{% url 'menu' %}" class="btn btn-secondary">See our new menu</a>
        </article>
      </div>

      <div class="col-md-4">
        <article class="text-center mb-4">
          <h2 class="fw-bold">Book a Table</h2>
          <img src="{% static 'img/bookatable.png' %}" alt="Book a Table" class="img-fluid rounded shadow">
          <p class="mt-3">
            Reserve your table
          </p>
          <a href="{% url 'book' %}" class="btn btn-secondary">Book your table now</a>
        </article>
      </div>

      <div class="col-md-4">
        <article class="text-center mb-4">
          <h2 class="fw-bold">Opening Hours</h2>
          <img src="{% static 'img/we-are-open.jpg' %}" alt="Opening Hours" class="img-fluid rounded shadow">
          <p class="mt-3">
            7 days a week, except for public holidays.
          </p>
          <ul class="list-unstyled">
            <li>Mon - Fri: 2pm - 10pm</li>
            <li>Sat: 2pm - 11pm</li>
            <li>Sun: 2pm - 9pm</li>
          </ul>
        </article>
      </div>
    </div>
  </section>

</div> 
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block content %}

<style>
  .toogle-button {
    max-width: 80px;
  }
</style>
<div class="container mt-5">
  <div class="row justify-content-center">
    <div class="col-md-6">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title text-center">User Login</h2>
          <form method="post" id="registrationForm">
            {% csrf_token %}
            {% for field in form %}
            <div class="mb-3">
              <label class="form-label">{{ field.label_tag }}</label>
              <div class="input-group">
                {{ field }}
                {% if field.name == "password" %}
                <button type="button" class="btn btn-sm btn-secondary toogle-button"
                  onclick="togglePassword()">Show</button>
                {% endif %}
              </div>
              {% if field.errors %}
              <div class="errorMessages">
                {% for error in field.errors %}
                <span class="errorMessage text-danger">{{ error }}</span>
                {% endfor %}
              </div>
              {% endif %}
            </div>
            {% endfor %}
            <div class="d-flex justify-content-between mt-3">
              <button type="submit" {% if request.user.is_authenticated %} disabled {% endif %}
                class="btn btn-primary">Login</button>
              <button type="reset" class="btn btn-danger">Reset</button>
            </div>
          </form>
        </div>
      </div>
    </div>
  </div>
</div>
</div>
<script>
  function togglePassword() {
    const passwordInput = document.querySelector('#id_password');
    if (passwordInput.type === 'password') {
      passwordInput.type = 'text';
    } else {
      passwordInput.type = 'password';
    }
  }
</script>
{% endblock %}